import pkg_resources
import datetime

# -- Project information -----------------------------------------------------

project = 'pg_dsp'
this_year = datetime.date.today().year
copyright = f'{this_year}, Damjan Rakanovic'
author = 'Damjan Rakanovic'

version = pkg_resources.get_distribution("pg_dsp").version
release = version

# extensions = [
#     'sphinx.ext.autodoc', 'sphinx.ext.githubpages', 'sphinxcontrib.tikz',
#     'sphinxcontrib.wavedrom', 'sphinx.ext.napoleon',
#     'sphinx_sitemap', 'sphinx.ext.autosectionlabel'
# ]

autosectionlabel_prefix_document = True

# site_url = "https://www.pygears.org/"

autodoc_default_options = {
    'show-inheritance': None,
    'members': None,
    'no-special-members': None,
    'exclude-members': 'mro, __weakref__,  __new__, __str__, __repr__',
}
autoclass_content = "class"
add_module_names = False

offline_skin_js_path = r"default.js"
offline_wavedrom_js_path = r"wavedrom.js"


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'
# html_title = "PyGears - HW Design: A Functional Approach"
# html_short_title = "PyGears"
# html_baseurl = "https://www.pygears.org"
# html_favicon = '_static/pygears.ico'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'travis_button': False,
    'github_user': 'damjanrak',
    'github_repo': 'pg_dsp',
    'github_banner': True,
    'description': 'HW Design: A Functional Approach',
    # 'logo': 'logo.png',
    # 'sidebar_width': '230px'
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# html_sidebars = {
#     '**': ['about.html', 'blog_link.html', 'globaltoc.html', 'searchbox.html']
# }

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'pygearsdoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    'preamble': r'''
    ''',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'pygears.tex', 'pygears Documentation', 'Damjan Rakanovic',
     'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, 'pygears', 'pygears Documentation', [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'pygears', 'pygears Documentation', author, 'pygears',
     'One line description of project.', 'Miscellaneous'),
]
